# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      # Compile program
      - name: Compile the program
        run: echo COMPILE1 >> ronald.txt # How to compile in terminal?
        
      # Execute program
      - name: Execute the program
        # run: echo EXECUTE # How to execute in terminal?
        
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
        
      # ------------------------------------------------------
      # EXEMPLE
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      # run: echo Hello, world!
        
      # EXEMPLE
      # Runs a set of commands using the runners shell
      # name: Run a multi-line script
      # run: |
      #   echo Add other actions to build,
      #   echo test, and deploy your project.
