# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:  
  repository_dispatch:
    types: [my-event]

  # Triggers the workflow on push event but only for the main branch
  

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      
      # Add MSBuild to the path https://github.com/marketplace/actions/setup-msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
         
      # Compile program
      - name: Compile the program
        id: create_build
        run: msbuild.exe .\WindowsProject1\
        env:
          BuildMode: StoreUpload 
          GenerateAppInstallerFile: true 
          #Configuration: Release # Default is Debug Mode
          
          
      # Upload the build artifacts: https://github.com/marketplace/actions/upload-artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: 'Build Debug mode'
          path:  'D:\a\windowsProject1\WindowsProject1\WindowsProject1'
          

