# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:  
  push:
       branches: [ main ]

  # Triggers the workflow on push event but only for the main branch
  

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Add MSBuild to the path
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
      # Compile program
      - name: Compile the program
        run: msbuild.exe
        
        
        
      # Execute program
      # - name: Execute the program
        # run: echo EXECUTE # How to execute in terminal?
